
/**
 * Module dependencies.
 */
'use strict';

var express = require('express')
  , routes = require('./routes')
  , http = require('http')
  , path = require('path')
  , nodemailer = require('nodemailer/lib/nodemailer');

var app = express();

var data = 
[
    {
      "title":"Kindling",
      "price": 249,
      "description": "Easily combustible small sticks or twigs used for starting a fire.",
      "type"  : 'sensors',
      "image" : 'images/products/kindling.png'
    },
    {
      "title": 'Matches',
      "price": 499,
      "description": "One end is coated with a material that can be ignited by frictional heat generated by striking the match against a suitable surface.",
      "type": 'sensors',
      "image": "images/products/matches.png",
    },
    {
      "title": 'Bow Drill',
      "price": 999,
      "description": 'The bow drill is an ancient tool. While it was usually used to make fire, it was also used for primitive woodworking and dentistry.',
      "type": 'boards',
      "image": 'images/products/bow-drill.png',
    },
    {
      "title": 'Tinder',
      "price": 499,
      "description": 'Tinder is easily combustible material used to ignite fires by rudimentary methods.',
      "type": 'boards',
      "image": 'images/products/tinder.png',
    },
    {
      "title": 'Birch',
      "price": 999,
      "description": 'Fresh and easily combustable',
      "type": 'robotics',
      "image": 'images/products/birch.png',
    }
];





app.configure(function(){
  app.set('port', process.env.PORT || 3000);
  app.set('views', __dirname + '/views');
  app.set('view engine', 'ejs');
  app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  //app.use(express.cookieParser('your secret here'));
  //app.use(express.session());
  app.use(app.router);
  app.use(express.static(path.join(__dirname, 'public')));
});

app.configure('development', function(){
  app.use(express.errorHandler());
});

app.get('/', routes.index);
// recipes
app.get('/recipes', function(req, res) {
    res.send(data);
});

app.post('/email', function(req, res) {


  var name = req.body.name;
  var address = req.body.address;
  var items = JSON.parse(req.body.items); // array of {prod, quantity, amount }


  console.log("items: "+items);
  console.log("name: "+name);
  console.log("address: "+address);

  var htmlStr = '<div>'+
        '<p>Name: '+name+'</p>'+
        '<p>Address: '+address+'</p>'+
        '<p>Item Info: </p>';

        var itemsStr = "<ul>";

        var total = 0; 
        for(var i = 0; i < items.length; i++){
            itemsStr += "<li>"+items[i].productName;

            itemsStr += " x "+items[i].quantity;
            itemsStr += "     Amount: "+(items[i].quantity * items[i].amount);

            total += (items[i].quantity * items[i].amount);

            itemsStr += "</li>";
        }
        itemsStr += "</ul>";

      htmlStr += itemsStr;

      htmlStr += "<p>Total: "+total+"</p>";
     htmlStr +=  '</div>';


  try{
  // create reusable transporter object using SMTP transport
  var transporter = nodemailer.createTransport("SMTP",{
    service: 'Gmail',
    auth: {
        user: 'frd.concepcion@gmail.com',
        pass: 'F3rdin@nd'
    }
  });

  // setup e-mail data with unicode symbols
  var mailOptions = {
      from: 'frd.concepcion@gmail.com', // sender address
      to: 'tonnyquintos@gmail.com', // list of receivers
      subject: 'Hello ', // Subject line
      text: 'Hello world', // plaintext body
      html: htmlStr// html body
  };

  // send mail with defined transport object
  transporter.sendMail(mailOptions, function(error, info) {
      if (error) {
          console.log(error);
      } else {
          console.log('Message sent: ' + info.response);
      }
  });

}catch(e){
  console.log("error ");
  console.log(e);
}

});


http.createServer(app).listen(app.get('port'), function(){
  console.log("Express server listening on port " + app.get('port'));
});
