
/**
 * Module dependencies.
 */

var express = require('express')
  , routes = require('./routes')
  , http = require('http')
  , path = require('path');

var app = express();

var data = 
[
    {
      "title":"Tonny_Kindling",
      "price": 249,
      "description": "Easily combustible small sticks or twigs used for starting a fire.",
      "type"  : 'sensor',
      "image" : 'images/products/kindling.png'
    },
    {
      "title": 'Tonny_Matches',
      "price": 499,
      "description": "One end is coated with a material that can be ignited by frictional heat generated by striking the match against a suitable surface.",
      "type": "sensor",
      "image": "images/products/matches.png",
    },
    {
      "title": "Tonny_Bow Drill",
      "price": 999,
      "description": 'The bow drill is an ancient tool. While it was usually used to make fire, it was also used for primitive woodworking and dentistry.',
      "type": 'microcontroller',
      "image": 'images/products/bow-drill.png',
    },
    {
      "title": 'Tonny_Tinder',
      "price": 499,
      "description": 'Tinder is easily combustible material used to ignite fires by rudimentary methods.',
      "type": 'microcontroller',
      "image": 'images/products/tinder.png',
    },
    {
      "title": 'Tonny_Birch Bark Shaving',
      "price": 999,
      "description": 'Fresh and easily combustable',
      "type": 'microcontroller',
      "image": 'images/products/birch.png',
    }
];

app.configure(function(){
  app.set('port', process.env.PORT || 3000);
  app.set('views', __dirname + '/views');
  app.set('view engine', 'ejs');
  app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  //app.use(express.cookieParser('your secret here'));
  //app.use(express.session());
  app.use(app.router);
  app.use(express.static(path.join(__dirname, 'public')));
});

app.configure('development', function(){
  app.use(express.errorHandler());
});

app.get('/', routes.index);
// recipes
app.get('/recipes', function(req, res) {
    res.send(data);
});

http.createServer(app).listen(app.get('port'), function(){
  console.log("Express server listening on port " + app.get('port'));
});
